CREATE TABLE IF NOT EXISTS public.court_case_claim_links (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id bigint NOT NULL,
    claim_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS court_case_claim_links_case_id_claim_id_key
  ON public.court_case_claim_links (case_id, claim_id);
CREATE INDEX IF NOT EXISTS idx_case_claim_links_case ON public.court_case_claim_links (case_id);
CREATE INDEX IF NOT EXISTS idx_case_claim_links_claim ON public.court_case_claim_links (claim_id);
