-- SQL для создания таблицы статусов писем и поля status_id
CREATE TABLE IF NOT EXISTS letter_statuses (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  color varchar NULL
);

ALTER TABLE letters
  ADD COLUMN IF NOT EXISTS status_id bigint REFERENCES letter_statuses(id);
