-- Recreate claims table according to new specification
DROP TABLE IF EXISTS claims CASCADE;
CREATE TABLE claims (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id INT,
    unit_ids BIGINT[] DEFAULT ARRAY[]::BIGINT[],
    claim_status_id INT,
    claim_no TEXT NOT NULL,
    claimed_on DATE,
    accepted_on DATE,
    registered_on DATE,
    resolved_on DATE,
    engineer_id UUID,
    ticket_ids BIGINT[] DEFAULT ARRAY[]::BIGINT[] REFERENCES tickets(id),
    description TEXT,
    attachment_ids BIGINT[] DEFAULT ARRAY[]::BIGINT[],
    created_by UUID,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_by UUID,
    updated_at TIMESTAMPTZ DEFAULT now()
);
