-- Recreate claims table according to new specification
DROP TABLE IF EXISTS claims CASCADE;
CREATE TABLE claims (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id INT REFERENCES projects(id) ON DELETE SET NULL,
    unit_ids BIGINT[] DEFAULT ARRAY[]::BIGINT[],
    claim_status_id INT REFERENCES claim_statuses(id) ON DELETE SET NULL,
    claim_no TEXT NOT NULL,
    claimed_on DATE,
    accepted_on DATE,
    registered_on DATE,
    resolved_on DATE,
    engineer_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
    -- Перечень связанных тикетов-дефектов
    ticket_ids BIGINT[] DEFAULT ARRAY[]::BIGINT[],
    description TEXT,
    attachment_ids BIGINT[] DEFAULT ARRAY[]::BIGINT[],
    created_by UUID REFERENCES profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_by UUID REFERENCES profiles(id) ON DELETE SET NULL,
    updated_at TIMESTAMPTZ DEFAULT now()
);
