-- Remove old column
ALTER TABLE defects DROP COLUMN IF EXISTS fix_cost;
-- Add new reference fields
ALTER TABLE defects ADD COLUMN defect_type_id integer REFERENCES defect_types(id);
ALTER TABLE defects ADD COLUMN defect_status_id integer REFERENCES defect_statuses(id);
ALTER TABLE defects ADD COLUMN received_at date;

-- Create defect_statuses table
CREATE TABLE IF NOT EXISTS defect_statuses (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL
);
